### ISSUE TITLE
Using ghostjs with karma

### ISSUE THREAD

**Issue by bfitch** [KevinGrandon/ghostjs#113] opened 2016-08-11 17:49 UTC
Hi @KevinGrandon, thanks for this great project!

I'm trying to use ghostjs with the karma test runner and I'm running into some issues with how ghost is bundled and imported via webpack/babel.

Is is possible to use ghostjs outside the `ghostjs` executable you've included? Could I `npm install ghostjs`, write a test like this:

``` js
import ghost from 'ghostjs';

describe('open a webpage', () => {
  it('prints some html', async () => {
    await ghost.open('http://localhost:8085')
    const body = await ghost.findElement('body')
    console.log(body.html())
  });
});
```

and run it with `karma`:

```
node_modules/.bin/karma start karma.config.js`
```

Currently I'm getting this error:

```
                      Asset     Size  Chunks             Chunk Names
test/acceptance/foo-test.js  5.99 kB       0  [emitted]  test/acceptance/foo-test.js
chunk    {0} test/acceptance/foo-test.js (test/acceptance/foo-test.js) 1.4 kB [rendered]
    [0] ./test/acceptance/foo-test.js 1.4 kB {0} [built] [1 error]

ERROR in ./~/ghostjs/src/ghostjs.js
Module parse failed: /Users/bfitch/src/chirp-nav-bar/node_modules/ghostjs/src/ghostjs.js Unexpected token (76:8)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (76:8)
```

I have a full `stage-0` babel environment in my project and played around with having webpack compile `node_modules/ghostjs/src/`, but am still running into problems. Perhaps another solution would be to provide an ES5 compiled export from ghostjs?

Either way, it would be really awesome to use the ghostjs api outside the `ghostjs` test runner (wrapper around mocha).  Thanks for any tips and, again, thanks for a great library-- I hope to use it soon!

**Comment by KevinGrandon** [comment] 2016-08-11 18:08
Hello @bfitch, thank you for filing the issue. Right now ghostjs has only really only been tested with mocha, but I'd be fine adding karma support as well. I have not tested it yet, but we might need to make some core changes to ghost to support it if it does not yet work.

If we need to make core changes, we might have to shell out to the karma binary from the ghost script here (possibly based on some environment variable): https://github.com/KevinGrandon/ghostjs/blob/7856cc55eaaea516d37628dc452cc6ff91eacbbd/ghostjs-core/bin/ghostjs#L27-L29

So you'd still run ghost tests from ./node_modules/.bin/ghostjs, but this would use the karma test runner.

Anyway I'll look more into this over the next few days and will keep this issue updated.

**Comment by bfitch** [comment] 2016-08-11 19:23
Awesome! Thanks for the quick response and for looking into it. If you need a tester, please let me know. I'd be happy to give a dev branch a spin.

**Comment by chrislloyd** [comment] 2016-10-31 12:19
@KevinGrandon why does ghost need to specifically support _any_ test runner? Most of it's functionality is library-like, except for the binary.

**Comment by KevinGrandon** [comment] 2016-10-31 16:38
Yes, it is library-like, the problem is that currently it only supports node and karma runs tests in the browser I believe? I believe there's far too many pieces in the phantomjs/test runner work flow that depend on node so it would be a nightmare to get this working from within the browser environment. Currently this expects mocha by default, and I don't think it's unreasonable to expect a project to use karma + mocha (for ghost tests). It's much better than karma + selenium.

In any case, going to close this for now as it should be fine to use karma alongside mocha/ghost, and it's currently not feasible to proxy the commands from another browser to phantom.

I bet this could work with the karma-nodeunit plugin though, I just haven't had time to test it.

**Closed by KevinGrandon** 2016-10-31 16:38 UTC
